#+title: Minecraft Event System
#+author: Dylan Garvis
#+date: <2023-11-21 Tue>

* Overview
The primary goal of this system is to tie together the in game chat between seperate minecraft servers.
To acomplish this, an event system is implemented that focus on chat messages and server join events
in the first version, however, could easily be expanded to have more events added or other applications
listening.

* Architecture
The system is made up of two parts
- Messaging Bus :: Kafka is used as the messaging bus and handles queues that severs can publish and 
  subscribe to.
- Spigot Plugin :: This is a java plugin that publishes events into the messages bus and listens to events
  to react to them.
- BungeeCord Plugin :: This is a java plugin that publishes events into the message for bungeecord.

** Types of Messages
In this inital implementation, there are two types of messages:
- ChatMessagePublished :: Message is published when a player sends a message.
  #+begin_src json 
  {
    "eventType": "CHAT_MESSAGE_PUBLISHED",
    "server": "string",
    "playerUUID": "string",
    "playerName": "string",
    "message": "string"
  }
  #+end_src
- PlayerJoinedServer :: Message is published when a player connects to a specific server.
  #+begin_src json
  {
    "eventType": "PLAYER_JOINED_SERVER",
    "server": "string",
    "playerUUID": "string",
    "playerName": "string"
  }
  #+end_src
- PlayerDisconnected :: Message is published when a player disconnects from a bungeecord network.
  #+begin_src json
  {
    "eventType": "PLAYER_DISCONNECTED",
    "playerUUID": "string",
    "playerName": "string"
  }
  #+end_src
- PlayerMoved :: Message is published when a player moves
  #+begin_src json
  {
    "eventType": "PLAYER_MOVED",
    "playerUUID": "string",
    "playerName": "string",
    "server": "string",
    "fromWorld": "string",
    "fromX": double,
    "fromY": double,
    "fromZ": double,
    "toWord": "string",
    "toX": double,
    "toY": double,
    "toZ": double
  }
  #+end_src
- BlockBroken :: Message is published when a player breaks a block
  #+begin_src json
  {
    "eventType": "BLOCK_BROKEN",
    "playerUUID": "string",
    "playerName": "string",
    "server": "string",
    "blockType": "string",
    "x": double,
    "y": double,
    "z": double
  }
  #+end_src

** Plugin Commands
Interaction with the plugin should be simple, where the jar file itself is just placed within the plugin directory
for bukkit.

From within the game, an op level user may use the following commands:
- /mcevents connect <server name> <kafka url> :: Which will establish the name of the server
  and connect to the kafka system to publish and listen for messages.
- /mcevents disconnect :: which will clear the config.
* Note
While building this series of plugins, it looks like a chat and player announce across all
servers in the network might be doable with only a bungeecord plugin. Based on a very quick
glance at the docs, it can see chat messages and can send messages to other servers the
sending player is not on. It could also do the same with connect and disconnect status.
